# FROM gradle:8-jdk21-alpine AS build
# COPY --chown=gradle:gradle . /home/gradle/src
# WORKDIR /home/gradle/src
# RUN gradle build --no-daemon -x test

# FROM eclipse-temurin:21-jre-alpine
# EXPOSE 8080
# COPY --from=build /home/gradle/src/build/libs/*-SNAPSHOT.jar app.jar
# ENTRYPOINT ["java", "-jar", "/app.jar"]